// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoepkipAPI.Data.Context;

#nullable disable

namespace SoepkipAPI.Migrations
{
    [DbContext(typeof(TrashContext))]
    [Migration("20250618100210_tashItem update")]
    partial class tashItemupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SoepkipAPI.Models.TrashItem", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("actual_temp_celsius")
                        .HasColumnType("float");

                    b.Property<float>("confidence")
                        .HasColumnType("float");

                    b.Property<float?>("feels_like_temp_celsius")
                        .HasColumnType("float");

                    b.Property<float?>("latitude")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<float?>("longditude")
                        .HasColumnType("float");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("weather_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("wind_direction")
                        .HasColumnType("float");

                    b.Property<float?>("wind_force_bft")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Trash");
                });
#pragma warning restore 612, 618
        }
    }
}
