name: backend publish

env: # Change these settings when you need to
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 8.0.x
  PUBLISH_DIRECTORY: "./out/publish"
on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_CORE_VERSION}}

      - name: Test
        run: dotnet test ./Soepkip-API.tests --no-build --verbosity normal

        
  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          context: ./Soepkip-API
          file: Soepkip-API/Dockerfile
          target: build
          load: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./Soepkip-API
          file: Soepkip-API/Dockerfile
          platforms: linux/amd64
          push: true
          target: final
          tags: ${{ vars.DOCKER_USERNAME }}/soepkip-api:latest

      - name: Pull the image to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull ${{ vars.DOCKER_USERNAME }}/soepkip-api:latest
            sudo docker stop soepkip-api || true
            sudo docker rm soepkip-api || true
            eval "sudo docker run -d $(echo '${{vars.PUBLISH_PORTS}}' | sed 's/,/ -p /g' | sed 's/^/-p /') -e CONNECTION_STRING_MYSQL='${{ secrets.CONNECTION_STRING_MYSQL }}' -e JWT_KEY_MONITORING='${{ vars.JWT_KEY_MONITORING }}' -e JWT_KEY_SENSORING='${{ vars.JWT_KEY_SENSORING }}' -e JWT_ISSUER='${{ vars.JWT_ISSUER }}' -e JWT_AUDIENCE='${{ vars.JWT_AUDIENCE }}'  --name soepkip-api ${{ vars.DOCKER_USERNAME }}/soepkip-api:latest"
